function getROICategory(roi) {
  if (roi < 0) {
    return {
      label: "Negative",
      className: "roi-negative",
    };
  }

  if (roi < 100) {
    return {
      label: "Low",
      className: "roi-low",
    };
  }

  if (roi < 300) {
    return {
      label: "Moderate",
      className: "roi-moderate",
    };
  }

  if (roi < 500) {
    return {
      label: "High",
      className: "roi-high",
    };
  }

  return {
    label: "Very High",
    className: "roi-very-high",
  };
}

function formatCurrency(value) {
  if (value === undefined || value === null || value === "") {
    return "N/A";
  }

  return `₹${Number(value).toLocaleString("en-IN")}`;
}

function PredictionResult({ result, campaign, onReset }) {
  if (!result) {
    return null;
  }

  const data = result.data || result;

  const predictedROI = Number(data.predicted_roi);

  const roiCategory = getROICategory(predictedROI);

  return (
    <section className="prediction-result">
      {/* ========================= */}
      {/* RESULT HEADER */}
      {/* ========================= */}

      <div className="result-header">
        <div>
          <p>MODEL PREDICTION</p>

          <h2>Estimated Campaign ROI</h2>
        </div>

        <span className={`prediction-badge ${roiCategory.className}`}>
          {roiCategory.label}
        </span>
      </div>

      {/* ========================= */}
      {/* ROI VALUE */}
      {/* ========================= */}

      <div className="roi-value">
        {Number.isFinite(predictedROI) ? `${predictedROI.toFixed(2)}%` : "N/A"}
      </div>

      <p className="roi-description">
        Estimated return on investment generated by the active machine learning
        model.
      </p>

      {/* ========================= */}
      {/* CAMPAIGN SUMMARY */}
      {/* ========================= */}

      <div className="result-section">
        <div className="result-section-header">
          <p>CAMPAIGN SUMMARY</p>

          <h3>Campaign Information</h3>
        </div>

        <div className="campaign-summary-grid">
          <div>
            <span>Campaign</span>

            <strong>{campaign?.campaign_name || "N/A"}</strong>
          </div>

          <div>
            <span>Budget</span>

            <strong>{formatCurrency(campaign?.budget)}</strong>
          </div>

          <div>
            <span>Duration</span>

            <strong>
              {campaign?.campaign_duration_days
                ? `${campaign.campaign_duration_days} days`
                : "N/A"}
            </strong>
          </div>

          <div>
            <span>Platform</span>

            <strong>{campaign?.platform || "N/A"}</strong>
          </div>

          <div>
            <span>Region</span>

            <strong>{campaign?.region || "N/A"}</strong>
          </div>

          <div>
            <span>Campaign Type</span>

            <strong>{campaign?.campaign_type || "N/A"}</strong>
          </div>
        </div>
      </div>

      {/* ========================= */}
      {/* MODEL INFORMATION */}
      {/* ========================= */}

      <div className="result-section">
        <div className="result-section-header">
          <p>MODEL INFORMATION</p>

          <h3>Prediction Details</h3>
        </div>

        <div className="result-details">
          <div>
            <span>Model</span>

            <strong>{data.model_name || "Campaign ROI Random Forest"}</strong>
          </div>

          <div>
            <span>Version</span>

            <strong>{data.model_version || "1.0.0"}</strong>
          </div>

          <div>
            <span>Prediction Latency</span>

            <strong>
              {data.prediction_latency_ms !== undefined
                ? `${Number(data.prediction_latency_ms).toFixed(3)} ms`
                : "N/A"}
            </strong>
          </div>
        </div>
      </div>

      {/* ========================= */}
      {/* ACTION */}
      {/* ========================= */}

      <button type="button" className="secondary-button" onClick={onReset}>
        Create Another Prediction
      </button>
    </section>
  );
}

export default PredictionResult;
